name: Build-Test
permissions:
  contents: read
  pull-requests: write
  issues: write
# Controls when the action will run. 
# Triggers the workflow on push events but only for the master branch.
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled, review_requested, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_26.2.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint via Fastlane
      run: bundle exec fastlane ci_lint

    - name: Run Unit Tests
      run: bundle exec fastlane ci_iOS

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: fastlane/coverage.lcov
        if-no-files-found: error
  run-sonar-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Check Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Get Sonar Quality Gate
        id: sonar
        run: |
          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=luizhammeli_Tets-Proj-CI" \
          | jq -r '.projectStatus.status')
          echo "status=$STATUS" >> $GITHUB_OUTPUT
      - name: Get Sonar Metrics
        id: sonar_metrics
        run: |
          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/measures/component?component=luizhammeli_Tets-Proj-CI&metricKeys=coverage,bugs,vulnerabilities,code_smells")
          COVERAGE=$(echo $RESPONSE | jq -r '.component.measures[] | select(.metric=="coverage") | .value')
          BUGS=$(echo $RESPONSE | jq -r '.component.measures[] | select(.metric=="bugs") | .value')
          VULNS=$(echo $RESPONSE | jq -r '.component.measures[] | select(.metric=="vulnerabilities") | .value')
          SMELLS=$(echo $RESPONSE | jq -r '.component.measures[] | select(.metric=="code_smells") | .value')

          echo "coverage=${COVERAGE: -0}" >> $GITHUB_OUTPUT
          echo "bugs=${BUGS: -0}" >> $GITHUB_OUTPUT
          echo "vulnerabilities=${VULNS: -0}" >> $GITHUB_OUTPUT
          echo "smells=${SMELLS: -0}" >> $GITHUB_OUTPUT
      
      - name: Debug Outputs
        run: |
          echo "Coverage: ${{ steps.sonar_metrics.outputs.coverage }}"
          echo "Bugs: ${{ steps.sonar_metrics.outputs.bugs }}"
          echo "Vulns: ${{ steps.sonar_metrics.outputs.vulnerabilities }}"
          echo "Smells: ${{ steps.sonar_metrics.outputs.smells }}"

      - name: Comment PR with Sonar Summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          SONAR_STATUS: ${{ steps.sonar.outputs.status }}
          COVERAGE: ${{ steps.sonar_metrics.outputs.coverage }}
          BUGS: ${{ steps.sonar_metrics.outputs.bugs }}
          VULNS: ${{ steps.sonar_metrics.outputs.vulnerabilities }}
          SMELLS: ${{ steps.sonar_metrics.outputs.smells }}
        with:
          script: |
            const status = process.env.SONAR_STATUS;
            const coverage = process.env.COVERAGE;
            const bugs = process.env.BUGS;
            const vulns = process.env.VULNS;
            const smells = process.env.SMELLS;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              | Metric | Value |
              |--------|-------|
              | üìä Coverage | ${coverage}% |
              | üêû Bugs | ${bugs} |
              | üîê Vulnerabilities | ${vulns} |
              | üßπ Code Smells | ${smells} |
              `
            })
              
