name: CI-iOS

# Controls when the action will run. 
# Triggers the workflow on push events but only for the master branch.
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, labeled, review_requested, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Run SwiftLint via Fastlane
      run: bundle exec fastlane swiftlint

    - name: Run Project
      run: bundle exec fastlane ci_iOS
  
